### PR TITLE
Unify the Two Directions of the PCM<->Java Pojo Transformations

### PR DESCRIPTION
**Pull request by jGleitz**

### CODE REVIEW

**Review by HeikoKlare — CHANGES_REQUESTED** [review]
There are some `equivalencetest` artifacts that should probably not be contained in this PR?
Additionally, we should _not_ merge the Java2PCM and PCM2Java tests, as they represent completely different kind of tests : while PCM2Java is a kind of integration test for the transformations, Java2PCM is a system test including monitoring, executing build jobs and so on.

**Comment by jGleitz** [comment]
If we want to keep the test separate, I think we should reflect the difference in their names.

However, I am not convinced by the argument: To my mind, both directions are supposed to be integration test, however, for one direction the wrong test technique has been chosen. That's a bug, not a feature, and I think we don't need to reflect a bug in the names.

**Comment by HeikoKlare** [comment]
No, there is neither a bug nor a wrong choice in test techniques.

The PCM2Java tests perform the same kind of tests like all the other application tests: they produce changes to the Ecore models, which are propagated into the `VirtualModel`, which, except for the correct behavior of change monitor does not rely on further functionality outside the `VirtualModel` (thus it does not test any view functionality).

The Java2PCM tests, however, were supposed to test both the transformations as well as the functionality of using an external Java view, which requires monitoring of that view (with Eclipse builders, AST listeners and so on) and the conversion of external changes (AST changes) to Vitruv changes before applying them to the `VirtualModel`. A comparable PCM2Java test would basically open some EMF editor (such as a Sirius editor, a tree editor or something else) and perform changes in its representation.

Of course, we can reflect this by some naming adaptation, fitting PCM2Java in the general terminology and marking the Java2PCM tests (both for the POJO and the EJB mappings) with something that reflect that they test the external editor monitoring.

**Comment by jGleitz** [comment]
See, that's where we differ: not having tests that are independent of the editor monitoring is a test design error, from my point of view. Having the system tests *additionally* makes sense, of course, but they should contain much less and much broader tests than are required to test the Java->PCM transformation properly.

It's not that I don't get the intention, I just that think that it was a bad choice.

So we'll keep the tests projects separate. What do you think of the name `...java2pcm.monitortests`?

**Comment by HeikoKlare** [comment]
Actually, I think we do not differ that much but especially excluded one point by accident: the proper Java2PCM tests are, of course, missing. I did not want to argue that the current Java2PCM test also cover them, but obviously my comments gave that impression.
Whether the current tests have the proper granularity for system tests may be disputable. Probably, they are just "one level" above the integration tests we have for the other applications, also taking the editor into account, but are not as coarse-grained as an actual system test should be.

I first also thought about `...java2pcm.monitortests`, but actually the other tests also use a monitor ;-) What these tests use in addition is a monitored editor, so maybe something like `...java2pcm.editortests` would fit better?

**Comment by jGleitz** [comment]
>  so maybe something like `...java2pcm.editortests` would fit better?

Good point. I’ll use that.

**Comment by jGleitz** [comment]
I removed the equivalence testing artefacts and applied the naming conventions we agreed on.

**Comment by HeikoKlare** [comment]
Great, thanks! I have adapted the EJB tests to also use an `editortests` namespace, because they are actually editor tests just like the POJO tests for Java->PCM.
I have also removed the `java2pcm` part from the project namespaces, because the projects could actually also contain editortests from PCM to Java and it seems to be cleaner to not have the direction in the project namespace. The ordinary PCM-Java tests only have the PCM->Java direction in their project and they don't have the direction in the project namespace either.
Additionally, I adapted the namespaces of the classes to match the project namespaces (and the naming of other tests).

**Review by HeikoKlare — APPROVED** [review]

**Pull request merged**
