### PR TITLE
Reactions: Detect Repository Subpackages in UML

### PR DESCRIPTION
**Pull request by jGleitz**
If a user creates the datatypes and contracts subpackages manually, the UML reactions should detect that (currently they ask what kind of component they should represent).

Reasons: 
 a) that’s how the Java<->PCM reactions do it
 b) if we _produce_ this structure after a Repository was created, we should also _consume_ this structure to create repository

### CODE REVIEW

**Comment by HeikoKlare** [comment]
I have to admit that I do not completely understand in which situation this is necessary. Is this the case if a repository and the corresponding packages are created once (no matter in which direction), then one of the subpackages is removed and inserted again?
Because otherwise I would expect that this is not necessary if I understand the current reactions correctly. If a repository is inserted, all packages are created. If a UML model is created and transformed to a PCM repository, the opposite transformation direction will create the missing packages. 

I understand that the behavior of the PCM-UML reactions is different to the PCM-Java ones, which is especially because the PCM-UML reactions have been developed as a _bidirectional_ transformation, whereas the PCM-Java ones are not. In fact, the PCM-Java reaction implementation is quite strange, because the Java->PCM direction changes the Java model as well.

**Comment by jGleitz** [comment]
> I have to admit that I do not completely understand in which situation this is necessary. 

If a user creates all three packages (i.e. repository package, datatypes package, contracts package) at once in UML. 

> If a UML model is created and transformed to a PCM repository, the opposite transformation direction will create the missing packages.

This is true. However, if the subpackages are created by the user directly, the transformations should also deal with this. The current behaviour is ‘the transformation must create the datatypes & contracts package’. The new behaviour is ‘the datatypes & contracts package must exist’ (no matter who created it)

**Comment by jGleitz** [comment]
By the way, this is a very nice example for a violation of the expectation we have been discussing on Slack: Three packages in UML and a repository in PCM should be an equivalence point of the transformation. However, it isn’t because there are states from which three packages in UML does not yield only a PCM repository.

**Comment by HeikoKlare** [comment]
I see. Of course, the contracts and datatypes package insertions are processed before executing the transformation in the opposite direction.

It is great that this also depicts and interesting example for the discussion we had :-)

**Review by HeikoKlare — APPROVED** [review]

**Comment by jGleitz** [comment]
The test failures are flaky tests again, aren’t they?

**Comment by HeikoKlare** [comment]
I think so, yes.

**Pull request merged**
