### PR TITLE
Support move for all objects in UML -> Java reactions, unify reactions style

### PR DESCRIPTION
**Pull request by JanWittler**
This PR adds support for move operations for all objects considered by the UML -> Java reactions (package, class, interface, enum, attribute, method, constructor) and streamlines all reactions to a unified design, removing the usage of compound triggers as described in #103.
Furthermore, the _createOrFind_ pattern was isolated such that the concepts of creating the correspondences and reacting to some change are now handled separately.

To refactor the reactions, there were several approaches possible how to deal with splitting the ```created and inserted``` pattern:
1. **Create the correspondence on create, handle insert like any other reaction**
  - intuitiv approach
  - _createOrFind_ pattern is only applied on creation
  - elements are unnamed
  - matching not possible for transitive cases
2. **Create the correspondence on insert, don't react to create**
  - close to current behaviour
  - _createOrFind_ pattern is applied with every insert instead of just at the beginning of the object's lifetime
  - matching possible for transitive cases if the object got named before insertion
  - previous reactions may get skipped as correspondence was not yet created
3. **Create the correspondence on rename, don't react to create**
  - requires a lot of changes to current behaviour
  - _createOrFind_ pattern is only applied if the old name value was empty
  - matching possible for transitive cases if the object got inserted before naming
  - previous reactions may get skipped as correspondence was not yet created

This PR chose to implement option 2. 
Option 1 can not deal with the transitive case and fails for some edge cases where a creation is not followed by an insertion to the expected parent (e.g. an association inserts the object also into the association but we don't want to create another object for that).
Option 3 shares the same downsides as option 2 but differs a lot from the current logic which would require more effort without having reasonable advantages over option 2.

However, the chosen solution as well as the current implementation make strong assumptions about the order in which objects are created. In particular, it is expected that an object is named before it is inserted (otherwise _createOrFind_ does not work) and even more critical, all other changes to the object are expected to be executed _after_ the insertion. If this is not the case, changes to an object performed prior to insertion are lost in the target model, as all such routines require an already setup correspondence. Currently, this can only be fixed by updating all attributes of an object when it is created, leading to a lot of code duplication (thus it's never done in the current code).
Therefore, it was desirable to solve this in the future as part of the language / the engine. Approaches for this could be to automatically reorder the changes such that naming and insertion are performed first. Another approach could be to extend the language by some ```await correspondence``` construct which queues up the routine until some correspondence is created. Furthermore, currently we assume for _createOrFind_ to work that an object is inserted *and* named thus it would make sense to allow compound triggers only for creation scenarios with required values, like ```created and features [name, eContainer] set```.

### CODE REVIEW

**Comment by JanWittler** [comment]
@HeikoKlare It seems that your recent changes to the UUID management and / or correspondences handling broke my test cases. They were working fine before the UUID refactoring changes were merged. Unfortunately, the failing tests are for move operations and thus newly added by this PR. I don't remember exactly which state was the last I used while it was working, but it should be a state from around Mon, 22/02.

When debugging the failures, the moved object (attribute / method / constructor) fails to get resolved by the UUID resolver. In particular, [this call](https://github.com/vitruv-tools/Vitruv/blob/26f813f1b47e33364da97d99d44158d0b089743b/bundles/framework/tools.vitruv.framework.correspondence/src/tools/vitruv/framework/correspondence/impl/InternalCorrespondenceModelImpl.xtend#L149) in ```InternalCorrespondenceModel``` returns ```false``` thus no correspondences are fetched. However, the passed object's container can be resolved to a UUID.

**Comment by JanWittler** [comment]
After investigating in detail, it seems that the newest changes changed the behaviour of objects detached from their resource. In particular, I reacted to the removal of objects from their container by removing the corresponding object from their container too. If subsequently an insert occurred, the same object got inserted. With the newest changes, the object is deleted when removed from the container and on insertion a new object is created.
I removed the reactions for removal from container to make things work again. A discussion why this is valid can be found in #102 .

**Comment by jGleitz** [comment]
> If subsequently an insert occurred, the same object got inserted.

That was indeed a bug of the previous change recording & propagation setup. This faulty behaviour hid multiple bugs in the applications.

**Comment by HeikoKlare** [comment]
I think I have not completely understood the issue yet: Do you insert the same object(s) you have removed from a container into the same or another container, or are there different objects that are then inserted? Because I first understood your situation to be the former one, and then, of course, the object(s) should be identified as being the same, such that no deletion and creation changes are added. However, because of the comment of @jGleitz I am not convinced that I got the issue correctly.

**Comment by JanWittler** [comment]
There is no issue anymore. I just wanted to raise awareness that the changes to UUID / TUID have changed some behaviour for detached objects but - as Joshua pointed out - this was already known. There were a lot of PRs last week, probably I just missed the one where this fix was highlighted.
 
> Do you insert the same object(s) you have removed from a container into the same or another container, or are there different objects that are then inserted?

Intended behaviour was the former but due to the recent framework changes the latter occurred. However, I fixed it in the reactions such that now the former is happening as intended.

**Comment by HeikoKlare** [comment]
> Intended behaviour was the former but due to the recent framework changes the latter occurred. 

Okay, that's interesting, because the former behavior is also how the framework is (still) intended to behave. So even if it's not an issue for you anymore, there is probably some bug in the UUID resolution mechanism. I'll have a look into that, but it does at least not seem to be that relevant for you anymore :-)

**Review by tsaglam — APPROVED** [review]
Looks good! I can find no issues here.

**Pull request merged**
